---

# Needed until markosamuli.pyenv handles it
- name: Add pyenv init command to zsh shell config
  ansible.builtin.lineinfile:
    path: "{{ lookup('env','HOME') }}/.zshrc"
    line: eval $(pyenv init --path)
    create: yes

- name: Set global python versions
  command: pyenv global {{ pyenv_python_versions | join(' ') }}

- name: Add pip shim to PATH
  ansible.builtin.lineinfile:
    path: "{{ lookup('env','HOME') }}/.zshrc"
    line: export PATH={{ lookup('env','HOME') }}/.pyenv/shims/pip:$PATH
    create: yes

- name: Add pipx apps to PATH
  ansible.builtin.lineinfile:
    path: "{{ lookup('env','HOME') }}/.zshrc"
    line: export PATH={{ lookup('env','HOME') }}/.local/bin:$PATH
    create: yes
