---

- name: install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: update
  shell: rustup update

- name: install nightly
  shell: rustup toolchain install nightly

- name: setup cargo on current shell
  shell: source {{ lookup('env','HOME') }}/.cargo/env
