---

- name: update
  ansible.builtin.command: rustup update

- name: install nightly
  ansible.builtin.command: rustup toolchain install nightly

- name: setup cargo on current shell
  ansible.builtin.command: source {{ lookup('env','HOME') }}/.cargo/env

- name: Add AWS Lambda platform
  # FIXME Is this needed on Linux?
  ansible.builtin.command: rustup target add x86_64-unknown-linux-musl
