---

- name: update
  shell: rustup update

- name: install nightly
  shell: rustup toolchain install nightly

- name: setup cargo on current shell
  shell: source {{ lookup('env','HOME') }}/.cargo/env
